from assistive_gym.envs.arm_manipulation_envs import (
    ArmManipulationBaxterEnv, ArmManipulationBaxterHumanEnv,
    ArmManipulationJacoEnv, ArmManipulationJacoHumanEnv,
    ArmManipulationPandaEnv, ArmManipulationPandaHumanEnv,
    ArmManipulationPR2Env, ArmManipulationPR2HumanEnv,
    ArmManipulationSawyerEnv, ArmManipulationSawyerHumanEnv,
    ArmManipulationStretchEnv, ArmManipulationStretchHumanEnv)
from assistive_gym.envs.bed_bathing_envs import (BedBathingBaxterEnv,
                                                 BedBathingBaxterHumanEnv,
                                                 BedBathingJacoEnv,
                                                 BedBathingJacoHumanEnv,
                                                 BedBathingPandaEnv,
                                                 BedBathingPandaHumanEnv,
                                                 BedBathingPR2Env,
                                                 BedBathingPR2HumanEnv,
                                                 BedBathingSawyerEnv,
                                                 BedBathingSawyerHumanEnv,
                                                 BedBathingStretchEnv,
                                                 BedBathingStretchHumanEnv)
from assistive_gym.envs.dressing_envs import (DressingBaxterEnv,
                                              DressingBaxterHumanEnv,
                                              DressingJacoEnv,
                                              DressingJacoHumanEnv,
                                              DressingPandaEnv,
                                              DressingPandaHumanEnv,
                                              DressingPR2Env,
                                              DressingPR2HumanEnv,
                                              DressingSawyerEnv,
                                              DressingSawyerHumanEnv,
                                              DressingStretchEnv,
                                              DressingStretchHumanEnv)
from assistive_gym.envs.drinking_envs import (DrinkingBaxterEnv,
                                              DrinkingBaxterHumanEnv,
                                              DrinkingJacoEnv,
                                              DrinkingJacoHumanEnv,
                                              DrinkingPandaEnv,
                                              DrinkingPandaHumanEnv,
                                              DrinkingPR2Env,
                                              DrinkingPR2HumanEnv,
                                              DrinkingSawyerEnv,
                                              DrinkingSawyerHumanEnv,
                                              DrinkingStretchEnv,
                                              DrinkingStretchHumanEnv)
from assistive_gym.envs.feeding_envs import (FeedingBaxterEnv,
                                             FeedingBaxterHumanEnv,
                                             FeedingBaxterMeshEnv,
                                             FeedingJacoEnv,
                                             FeedingJacoHumanEnv,
                                             FeedingJacoMeshEnv,
                                             FeedingPandaEnv,
                                             FeedingPandaHumanEnv,
                                             FeedingPandaMeshEnv,
                                             FeedingPR2Env, FeedingPR2HumanEnv,
                                             FeedingPR2MeshEnv,
                                             FeedingSawyerEnv,
                                             FeedingSawyerHumanEnv,
                                             FeedingSawyerMeshEnv,
                                             FeedingStretchEnv,
                                             FeedingStretchHumanEnv,
                                             FeedingStretchMeshEnv)
from assistive_gym.envs.human_testing import HumanTestingEnv
from assistive_gym.envs.scratch_itch_envs import (ScratchItchBaxterEnv,
                                                  ScratchItchBaxterHumanEnv,
                                                  ScratchItchBaxterMeshEnv,
                                                  ScratchItchJacoEnv,
                                                  ScratchItchJacoHumanEnv,
                                                  ScratchItchJacoMeshEnv,
                                                  ScratchItchPandaEnv,
                                                  ScratchItchPandaHumanEnv,
                                                  ScratchItchPandaMeshEnv,
                                                  ScratchItchPR2Env,
                                                  ScratchItchPR2HumanEnv,
                                                  ScratchItchPR2MeshEnv,
                                                  ScratchItchSawyerEnv,
                                                  ScratchItchSawyerHumanEnv,
                                                  ScratchItchSawyerMeshEnv,
                                                  ScratchItchStretchEnv,
                                                  ScratchItchStretchHumanEnv,
                                                  ScratchItchStretchMeshEnv)
from assistive_gym.envs.smplx_testing import SMPLXTestingEnv
